version: '3.7'
volumes:
  postgres_storage:
services:
  database:
    build:
      context: ./
      dockerfile: "db.Dockerfile"
#    restart: always
    ports:
      - "8081:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER_NAME}
  my_server:
    build:
      context: ./
      dockerfile: "server.Dockerfile"
    ports:
      - "5234:8080"
    depends_on:
      - database
    env_file:
      - .env
