version: '3.7'
volumes:
  postgres_storage:
services:
  database:
    build:
      context: ./build/db
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - "${DB_HOST_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - postgres_storage:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER_NAME}
  my_server:
    build:
      context: .
      dockerfile: "./build/api/Dockerfile"
    ports:
      - "${SERVER_HOST_PORT}:${SERVER_DOCKER_PORT}"
    depends_on:
      - database
    restart: always
    env_file:
      - .env
